<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Cisco Matthew</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*no </string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*shutdown</string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>access-list</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>crypto </string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>deny </string>
			<key>name</key>
			<string>support.constant.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>permit </string>
			<key>name</key>
			<string>constant.character.escape.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>object-group</string>
			<key>name</key>
			<string>markup.list.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>object</string>
			<key>name</key>
			<string>markup.list.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>host</string>
			<key>name</key>
			<string>markup.list.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[\s]*!(.*)</string>
			<key>name</key>
			<string>comment.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>static</string>
			<key>name</key>
			<string>constant.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>tunnel-group</string>
			<key>name</key>
			<string>support.class.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>crypto</string>
			<key>name</key>
			<string>support.class.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+\.\d+\.\d+\.\d+(/\d{1,2})?</string>
			<key>name</key>
			<string>constant.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]{0,2}:([0-9]{0,2}:)+[0-9]{0,2}\.[0-9]{0,3}</string>
			<key>name</key>
			<string>string11.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9a-fA-F]{0,4}:([0-9a-fA-F]{0,4}:)+[0-9a-fA-F]{0,4}(/\d{1,3})?</string>
			<key>name</key>
			<string>constant.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*(Jen|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dic) \d+</string>
			<key>name</key>
			<string>log.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^..(([0-9a-fA-F]{8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{0,8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{8})) </string>
			<key>name</key>
			<string>comment.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^..(([0-9a-fA-F]{8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{0,8}))</string>
			<key>name</key>
			<string>comment.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^..(([0-9a-fA-F]{8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{8}) ([0-9a-fA-F]{0,8}))</string>
			<key>name</key>
			<string>comment.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>certificate .*</string>
			<key>name</key>
			<string>comment.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>quit</string>
			<key>name</key>
			<string>comment.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.*&lt;.*&gt;.*</string>
			<key>name</key>
			<string>modifiche.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([S])tatus</string>
			<key>name</key>
			<string>string2.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^banner</string>
			<key>name</key>
			<string>comment.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^snmp-server.*</string>
			<key>name</key>
			<string>test11.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>( sh | show |#sh |#show |&gt;sh |&gt;show ).*</string>
			<key>name</key>
			<string>show.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>errdisable recovery .*</string>
			<key>name</key>
			<string>arancio.numeric.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string> any </string>
			<key>name</key>
			<string>string2.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>connected|Connected|Active|OK|Ready</string>
			<key>name</key>
			<string>connect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string> up </string>
			<key>name</key>
			<string>connect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(P\)</string>
			<key>name</key>
			<string>connect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(SU\)</string>
			<key>name</key>
			<string>connect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>secret.\d+</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>privilege.\d+.secret</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string> auto </string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>notconnect|Not connected|Removed|inactive| DOWN </string>
			<key>name</key>
			<string>notconnect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string> down | admin down | administratively down| down</string>
			<key>name</key>
			<string>notconnect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(D\)</string>
			<key>name</key>
			<string>notconnect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(SD\)</string>
			<key>name</key>
			<string>notconnect.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(I\)</string>
			<key>name</key>
			<string>arancione.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Standby</string>
			<key>name</key>
			<string>arancione.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>password.\d</string>
			<key>name</key>
			<string>rosso.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(a-|\s)10 </string>
			<key>name</key>
			<string>rosso.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(a-|\s)100 </string>
			<key>name</key>
			<string>giallo.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>a-half </string>
			<key>name</key>
			<string>giallo.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>( 1000 )</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(a-1000.|.a-1000)</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s10G\s)</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>full </string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string> a-full</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+disabled</string>
			<key>name</key>
			<string>arancione.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\smonitoring\s</string>
			<key>name</key>
			<string>string10.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>half</string>
			<key>name</key>
			<string>arancione.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^.\w.*(?=#)</string>
			<key>name</key>
			<string>giallo.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^.\w.*(?=&gt;)</string>
			<key>name</key>
			<string>giallo.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^hostname .*$</string>
			<key>name</key>
			<string>giallo.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>username</string>
			<key>name</key>
			<string>giallo.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>err-disabled</string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>changed state to down</string>
			<key>name</key>
			<string>rosso.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>changed state to up</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((Fa|Gi|Te)\d?/\d?/*\d*|Po\d+|Lo\d+|Vl\d+)</string>
			<key>name</key>
			<string>string7.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((Fas |Gig |Ten )\d?/\d?/*\d*)</string>
			<key>name</key>
			<string>string7.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((FastEthernet|GigabitEthernet|TenGigabitEthernet)\d?/\d?/*\d*|(Port-channel|FastEthernet|Vlan)\d+)</string>
			<key>name</key>
			<string>string7.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(interface|Interface)</string>
			<key>name</key>
			<string>string7.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(interface|Interface)</string>
			<key>name</key>
			<string>string7.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>description \w+.*</string>
			<key>name</key>
			<string>description.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>changed state to down</string>
			<key>name</key>
			<string>rosso.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>changed state to up</string>
			<key>name</key>
			<string>verde.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(10/100/1000BaseTX|10/100BaseTX)</string>
			<key>name</key>
			<string>test11.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(10/100/1000BaseTX|10/100BaseTX)</string>
			<key>name</key>
			<string>test11.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(10/100/1000BaseTX|10/100BaseTX)</string>
			<key>name</key>
			<string>test11.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>( Not Present)</string>
			<key>name</key>
			<string>rosso.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>username.\w+.(secret|password).\d.*</string>
			<key>name</key>
			<string>string8.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?!secret \d+ )\$.*$</string>
			<key>name</key>
			<string>comment.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>switchport mode trunk</string>
			<key>name</key>
			<string>string10.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>switchport mode access</string>
			<key>name</key>
			<string>string12.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>spanning.tree (portfast trunk|portfast)</string>
			<key>name</key>
			<string>string11.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+ip address.\d+\.\d+\.\d+.\d+.\d+\.\d+\.\d+.\d+.\d+</string>
			<key>name</key>
			<string>ip.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s+ip address .\d+\.\d+\.\d+.\d+.\d+\.\d+\.\d+.\d+.\d+ secondary</string>
			<key>name</key>
			<string>ip.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^aaa .*</string>
			<key>name</key>
			<string>string11.unquoted.cisco</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(vlan.\d+.*)</string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.cisco</string>
	<key>uuid</key>
	<string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
</dict>
</plist>
